baseURL = "https://nullmoon.org/"
languageCode = "en-us"
title = "slander"
theme = "hugo-xmin"
buildDrafts = true
enableGitInfo = true
disableHugoGeneratorInject = true

[permalinks]
 posts = "/:slug/"

[imaging]
 resampleFilter = "box"
 quality = 75
 anchor="smart"

 [markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
   unsafe = true
  [markup.highlight]
   lineNos = true
   style = "lovelace"
